services:
  db:
    image: mysql:8.0
    container_name: dongalleta_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DonGalleta
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    platform: linux/amd64

volumes:
  mysql_db_data: